server:
  port: 8080

spring:
  application:
    name: Spring-Boot-Reactive-Web-MongoDB
  data:
    mongodb:
      #      host: localhost
      #      port: 27777
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      uri: mongodb://localhost:27777/${MONGO_INITDB_DATABASE:cars}
      #      database: ${MONGO_INITIDB_DATABASE}
      authentication-database: admin

  docker:
    compose:
      file: ./compose.yml
      enabled: true
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs
